language: go

go:
- '1.10'

notifications:
  email: false

script:
# test and deploy 1-init/devops
- cd 1-init/devops
- make build
- make test
- make docker

env:
  global:
  #DOCKER_USERNAME:
  - secure: c+lOEq3nXkbPMwc17KzXDafYnGrzDVMKIGqlDCTxBxmnxC89uCdxY7lN+lO977WfZu2vXy3pucSnrZITwCzzykIIpvKjoUui7qkXv9rfanXiNCTXfdobn0rg2IYL+ahyQyM9UGiDKCNedxId7P5AtgENmvMKlBPi4i0KEqngf5YkSYTCNvKSRx55E+IlsbiqFMhuSnRRMa2KinXZ64i3L9J8xlfkr2rVvfEcSqXL1zIJrPXqskzQEp9F0qgzL3xd6mKHqTKgf2UjG+ps6fKOYOqjKpAImR/DNgUKZ9lFdYOMxiXqbNZESHta37rTaxZYKkL/4vnZT97vU+bwy+Q/i6Z1uiJN/wfKXTq8hTP9eW9DJgiTJA79hQ2aALbSDk1Nc0NkDfPNa7MGndRZckatXK8cBoM2Ke8ZTXmbdk7VPihjC+1q0gZJLyG0fq7PxhQdTJKK40e+Ol4nrlSBZKPrwzAjLZWCdSKEhD9T7bAGZWrqgr8mEQpS7TBTG++xMFKvLpMKodMp4B7zjF/aJ2aqnBUlPb8Sma02qHc0gksDxJEf/5F+G35Sni++K7UHvt2uNTABDo4tB8hPznkdnzyW9bteYODD5GhNh6nT4ISg0f8oSaQG9A8gmUu/Tjy+xXKgsE+DVnZ7t3Ioas3F0hZZTVp2sHynJQ6pH+2u7JV1pV4=
  #DOCKER_PASSWORD:
  - secure: ZQWairQyHSC2l13oItlqPPKb7C6ZQgzjbk2Mx+pKwGQO3Z617MF8E00AkI0PoVrEAbW7c+Dj4wC6huWKZIEP5OaZFDT+LcqN5Vv7UZZ+cwypj1+rwSO27YBwhvBRLWd19pA9oY0xHQUOrymrVTHMVx7JAaV4AKd04eJinXrcW0ahqiM2NgZZlKyAYLvAtu8ckadLixerGxqQDHDe7/9MQoOJEkeNd0Qg4ZTRsq4ca/NyPTsQRqfKtMrqPGQrJlKAmjXqRFLkrSkJOWDAFdQdt/Z+dYz0VFlMuPrCRHSPYYuO1EzKSTCt854itAxQXCPHHflgeIpX+rPPe/xMe9iwkljJt7uqYk/yPxL6573uUzUXaIpR0jrY+t8vxg0FqTOo7nMGs3wqbvR9CgSxFQwsfQ0SAw/xQG9Upr82EBjcPDu2RFJ7JVKBlH848FyPEi1ertxQk6PZF5KQHVR2Rij7IkpV3um1lT2o6b7wf23umoKK+Db6W2FR6UWcACLPMb39Z5pgRhUiJVMzYvRYk510WsCuvL9C8nHUKblgzhONkPXICGoh6wB+IYojQ29kFlTy/vogPB0CAGCg1JiUaFf0+2Y9iYZkN8zFEF/KA4cHHYQYbZrhy/y/AfwWtYYXqeuFAXw64Aq0617ckRu0DkKHNtAF/jsZoAIImkPOfaciVho=
